.PHONY: clean All

All:
	@echo "----------Building project:[ aula02 - Debug ]----------"
	@cd "aula02" && "$(MAKE)" -f  "aula02.mk"
clean:
	@echo "----------Cleaning project:[ aula02 - Debug ]----------"
	@cd "aula02" && "$(MAKE)" -f  "aula02.mk" clean
